const galleryData = [
  {
    id: 1,
    title: "Flower Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre1.png",
    likes: 124,
  },
  {
    id: 2,
    title: "Wooden varmala preservation",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood3.png",
    likes: 89,
  },
  {
    id: 3,
    title: "Customized Clock",
    category: "Clock",
    image: "Clocks/ClockBlack.png",
    likes: 70,
  },
  {
    id: 4,
    title: "Customized Clock",
    category: "Clock",
    image: "Clocks/Clock2.png",
    likes: 123,
  },
  {
    id: 5,
    title: "Wooden varmala preservation",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood1.png",
    likes: 134,
  },
  {
    id: 6,
    title: "Custom KeyChains",
    category: "Key Chains",
    image: "Keychains/KeyChain3.png",
    likes: 175,
  },
  {
    id: 7,
    title: "Custom KeyChains",
    category: "Key Chains",
    image: "Keychains/KeyChain2.png",
    likes: 162,
  },
  {
    id: 8,
    title: "Custom KeyChains",
    category: "Key Chains",
    image: "Keychains/KeyChain1.png",
    likes: 125,
  },
  {
    id: 9,
    title: "Wooden varmala preservation",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood4.png",
    likes: 89,
  },
  {
    id: 10,
    title: "Wooden varmala preservation",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood2.png",
    likes: 89,
  },
  {
    id: 11,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature1.png",
    likes: 89,
  },
  {
    id: 12,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature2.png",
    likes: 89,
  },
  {
    id: 13,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature3.png",
    likes: 189,
  },
  {
    id: 14,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature4.png",
    likes: 146,
  },
  {
    id: 15,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature5.png",
    likes: 349,
  },
  {
    id: 16,
    title: "Miniature",
    category: "Miniature",
    image: "Miniatures/Miniature6.png",
    likes: 145,
  },
  {
    id: 17,
    title: "Flower Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre2.png",
    likes: 124,
  },
  {
    id: 18,
    title: "Flower Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre3.png",
    likes: 163,
  },
  {
    id: 19,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray1.png",
    likes: 143,
  },
  {
    id: 20,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray2.png",
    likes: 133,
  },
  {
    id: 21,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray3.png",
    likes: 134,
  },
  {
    id: 22,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray4.png",
    likes: 144,
  },
  {
    id: 23,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray5.png",
    likes: 184,
  },
  {
    id: 24,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray6.png",
    likes: 144,
  },
  {
    id: 25,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray7.png",
    likes: 174,
  },
  {
    id: 26,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray8.png",
    likes: 164,
  },
  {
    id: 27,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray9.png",
    likes: 153,
  },
  {
    id: 28,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray10.png",
    likes: 144,
  },
  {
    id: 29,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray11.png",
    likes: 162,
  },
  {
    id: 30,
    title: "Resin Tray",
    category: "Resin Trays",
    image: "Trays/Tray12.png",
    likes: 182,
  },
  {
    id: 31,
    title: "Customized Clock",
    category: "Clock",
    image: "Clocks/Clock3.png",
    likes: 211,
  },
  {
    id: 32,
    title: "Custom KeyChains",
    category: "Key Chains",
    image: "Keychains/KeyChain4.png",
    likes: 213,
  },
  {
    id: 33,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood5.png",
    likes: 112,
  },
  {
    id: 34,
    title: "Candle Holders",
    category: "Resin Candle Holders",
    image: "Candles/Candle1.png",
    likes: 112,
  },
  {
    id: 35,
    title: "Candle Holders",
    category: "Resin Candle Holders",
    image: "Candles/Candle2.png",
    likes: 112,
  },
  {
    id: 36,
    title: "Candle Holders",
    category: "Resin Candle Holders",
    image: "Candles/Candle3.png",
    likes: 52,
  },
  {
    id: 37,
    title: "Candle Holders",
    category: "Resin Candle Holders",
    image: "Candles/Candle4.png",
    likes: 82,
  },
  {
    id: 38,
    title: "Customized Clock",
    category: "Clock",
    image: "Clocks/Clock4.png",
    likes: 211,
  },
  {
    id: 39,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood6.png",
    likes: 154,
  },
  {
    id: 40,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood7.png",
    likes: 154,
  },
  {
    id: 41,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood8.png",
    likes: 199,
  },
  {
    id: 42,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood9.png",
    likes: 162,
  },
  {
    id: 43,
    title: "Motivation Frame",
    category: "Wooden Frames",
    image: "WoodenFrames/Wood10.png",
    likes: 213,
  },
  {
    id: 44,
    title: "Flower Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre5.png",
    likes: 195,
  },
  {
    id: 45,
    title: "Flower Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre6.png",
    likes: 173,
  },
  {
    id: 46,
    title: " Arabic Preservation",
    category: "Preservation",
    image: "FlowerPreservation/FlowerPre7.png",
    likes: 284,
  },
  {
    id: 47,
    title: "Baby Memories",
    category: "New Born preservation",
    image: "NewBorn/NewBorn1.png",
    likes: 395,
  },
  {
    id: 48,
    title: "Baby Memories",
    category: "New Born preservation",
    image: "NewBorn/NewBorn2.png",
    likes: 307,
  },
  {
    id: 49,
    title: "Baby Memories",
    category: "New Born preservation",
    image: "NewBorn/NewBorn3.png",
    likes: 265,
  },
  {
    id: 50,
    title: "Baby Memories",
    category: "New Born preservation",
    image: "NewBorn/NewBorn4.png",
    likes: 294,
  },
];

export default galleryData;
